version: "3.7"

services:
  app:
    build:
      context: .
    volumes:
      - .:/go/src/twtbot
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017"
      MONGO_DATABASE_NAME: "tester"
      DISCORD_AUTH_TOKEN: "${DISCORD_AUTH_TOKEN}"
      ENV: "development"
  mongo:
    image: mongo:latest
    ports:
      - ${MONGO_PORT:-27017}:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: {}
